**Про приватность**
 - [Брюс Шнайер](https://ru.wikipedia.org/wiki/Шнайер,_Брюс):
  - [Партнёрство при слежке](http://www.cypherpunks.ru/Surveillance-partnership.html#Surveillance-partnership)
  - [Цена приватности](http://www.cypherpunks.ru/Privacy-value.html#Privacy-value)
  - [Приватность в современном мире](http://www.cypherpunks.ru/Modern-world-privacy.html#Modern-world-privacy)
  - [Секреты и ложь(книга)](http://flibusta.is/b/92638)
  - [Практическая криптография(книга)](http://flibusta.is/b/352928)
 - [Тайна личной жизни в современном мире](https://piratemedia.net/vse-vashi-dannye-prinadlezhat-nam-tayna-lichnoy-zhizni-sovremennom-mire )
 - [Взломщики кодов(книга)](http://flibusta.is/b/314483)
 - Про facebook:
  - [Состав досье на пользователя](https://geektimes.ru/post/279856/#comment_9534416)
  - [Как facebook использует BigData(политика)](http://theins.ru/politika/38490)
  - [Как facebook ищет связи между пользователями](https://geektimes.ru/post/279940/)
  - [Про WhatsApp и Facebook](https://geektimes.ru/post/279856/ )
 - Про google:
  - [6 ссылок о том, что Google знает о вас](https://geektimes.ru/post/241580/)
  - [Chromium не лучше Chrome](https://habrahabr.ru/post/101396/)
  - [Рекапча == рабство](https://habrahabr.ru/post/121010/)
 - Про Yandex
  - [Yandex исследует сны](https://yandex.ru/company/researches/2017/dreams)
 - [Краткий обзор последнего слива про шпионаж ЦРУ](http://www.opennet.ru/opennews/art.shtml?num=46157)
 - [GitHub не нужен](https://wubthecaptain.eu/articles/why-i-dont-support-github)
